### ISSUE TITLE
Error - RuntimeError: You must call "start" before calling "update" with progressbar library (progressbar==2.5)

### ISSUE THREAD

**Issue by KelumPerera** [anhduy41294/imageforensics#1]
Hi, I got following two errors with sample code of Error Level Analysis (ELA) and demosaicing artifacts (CFA). Appreciate if you can find a work around.
python foreimg.py -el demo.jpg

Analyzing...
Traceback (most recent call last):
  File "foreimg.py", line 761, in <module>
    main ()
  File "foreimg.py", line 81, in main
    ela(args.datafile, args.quality, args.blocksize )
  File "foreimg.py", line 526, in ela
    bar.update(5)
  File "C:\ProgramData\Anaconda2\lib\site-packages\progressbar\progressbar.py", line 257, in update
    raise RuntimeError('You must call "start" before calling "update"')
RuntimeError: You must call "start" before calling "update"

python foreimg.py -cf demo.jpg

Analyzing...
Traceback (most recent call last):
  File "foreimg.py", line 761, in <module>
    main ()
  File "foreimg.py", line 87, in main
    cfa_tamper_detection(args.datafile)
  File "foreimg.py", line 587, in cfa_tamper_detection
    bar.update(5)
  File "C:\ProgramData\Anaconda2\lib\site-packages\progressbar\progressbar.py", line 257, in update
    raise RuntimeError('You must call "start" before calling "update"')
RuntimeError: You must call "start" before calling "update"

**Comment by pakkunandy** [comment]
Have you installed all the required packages? It works fine with python 2.7, please check your python version (maybe). I just tested it, and it works fine. I'll check deeper later.

**Comment by KelumPerera** [comment]
Thanks for the reply, I'm using Python 2.7.15.
Versions of some libraries are as follows; 
numpy version: 1.15.4
argparse version: 1.1
json version: 2.0.9
exifread version: 2.1.2
OpenCV version: 4.0.0
pywt version: 1.0.1
progressbar version: 2.5
scipy version: 1.1.0
PIL version: 5.3.0
matplotlib version: 2.2.3
